### ISSUE TITLE
Broken with new beta insights

### ISSUE THREAD

**Issue by austinkregel** [daspecster/github-contributions-chrome-extension#7]
This plugin seems to be grabbing extra data which it doesn't need from GitHub's new Beta insights.

**Comment by austinkregel** [comment]
![screen shot 2018-09-14 at 11 16 46 am](https://user-images.githubusercontent.com/5355937/45559158-b5dd4e80-b80f-11e8-8275-edae60a53379.png)

**Comment by daspecster** [comment]
yeah :'(
